# Generated by Django 3.1.4 on 2020-12-16 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('users_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField()),
                ('is_group', models.BooleanField()),
                ('is_educational', models.BooleanField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.IntegerField(default=0)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dialogs.dialog')),
            ],
        ),
    ]
