# Generated by Django 3.1.4 on 2020-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_userdialog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdialog',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
