# Generated by Django 3.1.4 on 2020-12-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relations', '0001_initial'),
        ('dialogs', '0002_userdialog_user'),
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='refer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced', to='relations.userrelationmodel'),
        ),
        migrations.AddField(
            model_name='readmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='messages.message'),
        ),
        migrations.AddField(
            model_name='readmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to='relations.userrelationmodel'),
        ),
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='messages.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwardings', to='messages.message'),
        ),
    ]
