# Generated by Django 3.1.4 on 2020-12-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='messages.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forwarded',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwardings', to='messages.message'),
        ),
    ]
