# Generated by Django 3.1.4 on 2020-12-16 09:30

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.file_path)),
                ('size', models.FloatField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
